name: Build, Test & Release

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Установка JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Сборка и тесты
        run: mvn clean package -U -ntp

      - name: Проверка code style
        run: mvn spotless:check

      - name: Проверка tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "Running only for tags starting with v."]

      - name: Не tags v
        if: !startsWith(github.ref, 'refs/tags/v')
        run: echo "Running only if not v..."

      - name: Не tags вообще
        if: !startsWith(github.ref, 'refs/tags/')
        run: echo "Running only if not a tag."

      - name: Создание GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
        # .original а не просто .jar для демонстрации чтобы не занимать место uber jar-ом (~60 МБ)
          files: |
            target/*.jar.original
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
